
services:
  database:
    image: postgres:15.2-bullseye
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5438:5432 # Change port because of conflict on dev machine.
    volumes:  
      - database:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
  kafka:
    image: bitnami/kafka:latest
    volumes:
      - kafka_data:/bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAKFA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NODE_ID=1
  keycloak:
    image: keycloak/keycloak:21.1.2-0
    command: ["start-dev", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_REALM_NAME=saveup
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json:ro
volumes:
  database:
  kafka_data:
